import{a as m}from"./assets/vendor-7cacf7fc.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function u(r,s){const n=r.map(({webformatURL:o,largeImageURL:e,tags:t,likes:a,views:c,comments:p,downloads:d})=>`<li class = "list-item">
      <a href="${e}" ><img class="search-image" src = "${o}" alt = "${t}" ><div class="options">
      <p class="options-item"> likes:<span class="options-item-span">${a}</span></p>
      <p class="options-item"> views:<span class="options-item-span">${c}</span></p>
      <p class="options-item"> comments:<span class="options-item-span">${p}</span></p>
      <p class="options-item"> downloads:<span class="options-item-span">${d}</span></p></div>
    
      </a>
      
      </li>`).join("");s.insertAdjacentHTML("beforeend",n)}const f="https://pixabay.com",y="41909271-8b5dab2225a1cd5a9757159a5",g="api";function h(r){return m.get(`${f}/${g}`,{params:{key:y,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:1}}).then(({data:s})=>s)}const i={formEl:document.querySelector(".form-search"),galleryEL:document.querySelector(".gallery-images"),loadMoreEl:document.querySelector('[data-action="load-more"]')},l="is-hidden";i.formEl.addEventListener("submit",L);async function L(r){r.preventDefault(),i.galleryEL.innerHTML="";const s=r.currentTarget,n=s.elements.query.value.trim();if(n)try{const{hits:o}=await h(n);u(o,i.galleryEL),o.length>0?i.loadMoreEl.classList.remove(l):i.loadMoreEl.classList.add(l)}catch{console.log(err)}finally{s.reset()}}
//# sourceMappingURL=commonHelpers.js.map
