import{a as y,S as h,i as d}from"./assets/vendor-bad0427b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=l(e);fetch(e.href,s)}})();function p(i,r){const l=i.map(({webformatURL:o,largeImageURL:e,tags:s,likes:c,views:u,comments:f,downloads:g})=>`<li class = "list-item">
      <a href="${e}" ><img class="search-image" src = "${o}" alt = "${s}" ><div class="options">
      <p class="options-item"> likes:<span class="options-item-span">${c}</span></p>
      <p class="options-item"> views:<span class="options-item-span">${u}</span></p>
      <p class="options-item"> comments:<span class="options-item-span">${f}</span></p>
      <p class="options-item"> downloads:<span class="options-item-span">${g}</span></p></div>
    
      </a>
      
      </li>`).join("");r.insertAdjacentHTML("beforeend",l)}const E="https://pixabay.com",L="41909271-8b5dab2225a1cd5a9757159a5",b="api/";function m({query:i,page:r=1,per_page:l}){return y.get(`${E}/${b}`,{params:{key:L,q:i,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:l,page:r}}).then(({data:o})=>o)}const t={formEl:document.querySelector(".form-search"),galleryEL:document.querySelector(".gallery-images"),loadMoreEl:document.querySelector('[data-action="load-more"]'),preloader:document.getElementById("preloader")},v=new h(".gallery-images a",{captionDelay:250}),n="is-hidden",a={query:"",page:1,maxPage:0,per_page:40};t.formEl.addEventListener("submit",w);async function w(i){i.preventDefault(),t.galleryEL.innerHTML="",a.page=1;const r=i.currentTarget;if(a.query=r.elements.query.value.trim(),!a.query){d.show({title:"❌",messageColor:"white",message:"Sorry, You have not entered any word.Please try again!",position:"topRight",color:"red"});return}try{const{hits:o,totalHits:e}=await m(a);if(!e){t.loadMoreEl.classList.add(n),d.show({title:"❌",messageColor:"white",message:"Sorry, we dont have any pictures for your request.Please try again!",position:"topRight",color:"red"});return}a.maxPage=Math.ceil(e/a.pageSize),p(o,t.galleryEL),v.refresh(),o.length>0&&o.length!==e?(t.loadMoreEl.classList.remove(n),t.loadMoreEl.addEventListener("click",l)):t.loadMoreEl.classList.add(n)}catch{console.log(err)}finally{r.reset()}async function l(){a.page+=1,t.preloader.classList.remove(n),t.loadMoreEl.disabled=!0;try{const{hits:o}=await m(a);p(o,t.galleryEL)}catch(o){console.log(o)}finally{t.preloader.classList.add(n),t.loadMoreEl.disabled=!1,a.page===a.maxPage&&(t.loadMoreEl.classList.add(n),d.show({title:"Finish",messageColor:"white",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"blue"}),t.loadMoreEl.removeEventListener("click",l))}}}
//# sourceMappingURL=commonHelpers.js.map
